### ISSUE TITLE
JitsiMeetJS is not defined 

### ISSUE THREAD

**Issue by leofishman** [relm-us/jitsi-svelte#2]
I have installed:
    "@sveltejs/kit": "next",
    "svelte": "^3.34.0",
    "svelte-preprocess": "^4.7.3",
    "jitsi-svelte": "^0.4.0",
    "lib-jitsi-meet": "^1.0.6",
    "sirv-cli": "^1.0.12"

If I ran the example in the stand alone mode, it works fine, but when I copied the example code to my svelte src project, get an error:
[vite] Error when evaluating SSR module /node_modules/jitsi-svelte/src/jitsi/init.js:
ReferenceError: JitsiMeetJS is not defined
    at /node_modules/jitsi-svelte/src/jitsi/init.js:7:1
    at instantiateModule (/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68693:166)
JitsiMeetJS is not defined

I can't find where the library is loaded

**Comment by canadaduane** [comment]
Jitsi recommends loading the library from their server, rather than bundling a specific version (I don't consider this best practice, but they do, so I follow their lead). Here's where it's defined in the example:

https://github.com/relm-us/jitsi-svelte/blob/main/example/public/index.html#L10
